global_location = "North Europe"
resource_group_name = "gordion-rg"
vnet_name = "gordion-vnet"
default_subnet_name = "default-sn"
aks_subnet_name = "aks-sn"
aks_name = "gordion-aks-cluster"
public_ip_name = "gordion-pip"
appgw_name = "gordion-appgw"
appgw_ipconf_name = "gordion-ipconf"
storageacc_name = "gordion-sa"
storagecon_name = "greylogcon"
aks_storage_class = "graylogstorageclass"
# subscription id must be set
subscription_id = ""